In [3]:
import numpy as np
import pandas as pd 
from matplotlib import pyplot as plt
import seaborn as sns
import statistics as sts
from sklearn.preprocessing import StandardScaler,LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import f1_score,confusion_matrix,classification_report,precision_score,accuracy_score

In [6]:
df1=pd.read_csv(r"User_Data.csv",encoding_errors='ignore',delimiter=',')

df2=df1.copy()

In [8]:
df2.describe()

            User ID         Age  EstimatedSalary   Purchased
count  4.000000e+02  400.000000       400.000000  400.000000
mean   1.569154e+07   37.655000     69742.500000    0.357500
std    7.165832e+04   10.482877     34096.960282    0.479864
min    1.556669e+07   18.000000     15000.000000    0.000000
25%    1.562676e+07   29.750000     43000.000000    0.000000
50%    1.569434e+07   37.000000     70000.000000    0.000000
75%    1.575036e+07   46.000000     88000.000000    1.000000
max    1.581524e+07   60.000000    150000.000000    1.000000

In [9]:
df2.drop_duplicates(inplace=True)

In [10]:
df2.drop(columns=['User ID'],inplace=True)

In [13]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Gender           400 non-null    object
 1   Age              400 non-null    int64
 2   EstimatedSalary  400 non-null    int64
 3   Purchased        400 non-null    int64
dtypes: int64(3), object(1)
memory usage: 12.6+ KB

In [12]:
df2.dropna(axis=0,how='any',inplace=True)

In [16]:
df2['Gender'].unique()

array(['Male', 'Female'], dtype=object)

In [18]:
mapping={
    'Male':1,
    "Female":2
}
df2['gen_en']=df2['Gender'].map(mapping)

In [19]:
df2

     Gender  Age  EstimatedSalary  Purchased  gen_en
0      Male   19            19000          0       1
1      Male   35            20000          0       1
2    Female   26            43000          0       2
3    Female   27            57000          0       2
4      Male   19            76000          0       1
..      ...  ...              ...        ...     ...
395  Female   46            41000          1       2
396    Male   51            23000          1       1
397  Female   50            20000          1       2
398    Male   36            33000          0       1
399  Female   49            36000          1       2

[400 rows x 5 columns]

In [24]:
df2.rename(columns={"EstimatedSalary":"Ets","Purchased":"Psd","gen_en":"gen"},inplace=True)

In [25]:
df2.sample(10)

     Gender  Age     Ets  Psd  gen
160    Male   32  100000    1    1
156    Male   46   59000    0    1
284    Male   48  141000    0    1
384  Female   57   33000    1    2
146  Female   27   96000    1    2
24     Male   46   23000    1    1
264    Male   48   90000    1    1
186  Female   20   82000    0    2
291    Male   49   89000    1    1
170    Male   21   88000    0    1

In [27]:
df3=pd.DataFrame(data=df2,columns=['Age','Ets','gen','Psd'],dtype='int')

In [28]:
df3.sample(2)

     Age     Ets  gen  Psd
95    35   44000    2    0
103   33  149000    2    1

In [34]:
round(df3.corr(method="pearson"),2)

      Age   Ets   gen   Psd
Age  1.00  0.16  0.07  0.62
Ets  0.16  1.00  0.06  0.36
gen  0.07  0.06  1.00  0.04
Psd  0.62  0.36  0.04  1.00

In [33]:
round(df3.corr(method="spearman"),2)

      Age   Ets   gen   Psd
Age  1.00  0.12  0.07  0.61
Ets  0.12  1.00  0.04  0.31
gen  0.07  0.04  1.00  0.04
Psd  0.61  0.31  0.04  1.00

In [35]:
df3.columns

Index(['Age', 'Ets', 'gen', 'Psd'], dtype='object')

In [36]:
x=df3[['Age', 'Ets', 'gen']]
y=df3['Psd']

In [38]:
df3.size

1600

In [39]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [57]:
logistic_regression=LogisticRegression(solver="liblinear")

logistic_regression.fit(x_train,y_train)

y_Psd=logistic_regression.predict_proba(x_test)

y_psd1=logistic_regression.predict(x_test)
print(y_psd1)

print(classification_report(y_test,y_psd1))
print(precision_score(y_test,y_psd1))
print(accuracy_score(y_test,y_psd1))
print(f1_score(y_test,y_psd1))

[0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 1 0 1 0 0 0 1 0 1 0 0
 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0
 0 0 1 0 0 0]
              precision    recall  f1-score   support

           0       0.72      0.92      0.81        52
           1       0.69      0.32      0.44        28

    accuracy                           0.71        80
   macro avg       0.70      0.62      0.62        80
weighted avg       0.71      0.71      0.68        80

0.6923076923076923
0.7125
0.43902439024390244

In [58]:
import joblib 

joblib.dump(logistic_regression,"purchased.joblib")

['purchased.joblib']

x=df3[['Age', 'Ets', 'gen']]
y=df3['Psd']

In [60]:
df3.describe()

              Age            Ets         gen         Psd
count  400.000000     400.000000  400.000000  400.000000
mean    37.655000   69742.500000    1.510000    0.357500
std     10.482877   34096.960282    0.500526    0.479864
min     18.000000   15000.000000    1.000000    0.000000
25%     29.750000   43000.000000    1.000000    0.000000
50%     37.000000   70000.000000    2.000000    0.000000
75%     46.000000   88000.000000    2.000000    1.000000
max     60.000000  150000.000000    2.000000    1.000000

In [ ]:
import pandas as pd 
import streamlit as st
import joblib 

try:
    logistic_model=joblib(r"purchased.joblib")
    st.title("Product is purchased or not")
    st.write("Logistic model is loaded succesfully with solver is liblinear ")
    st.header('''if "0" means not purchase || if "1" means product is purchased ''')
    st.success("Model loaded success")
    st.balloons()
    st.sidebar("Choose the input parameters")
    with st.sidebar.form(key="input parameters"):
        with st.sidebar:
            Age=st.number_input("AGE",min_value=18,max_value=90,value=45)
            Ets=st.number_input("ETS",min_value=10000,max_value=10000000,value=83457)
            Gen=st.number_input("GEN",min_value=1,max_value=2,value=1,help="1 is male and 2 is female")
            submit_button=st.form_submit_button(label='Submit')
        if submit_button:
            st.success("Form is submitted succesfully ....!")
            model_dict={
                "Age":Age,
                "Ets":Ets,
                "gen":Gen
            }
            df4=pd.DataFrame(data='model_dict',index=[0])
            st.table(df4)
            preditations=logistic_model.predict(df4)
            st.code(f"Purchased or not is {abs(preditations[0]):,.2f}")
            st.header("Barchart")
            st.bar_chart(df4)    
        else:
            st.warning("Form is not submitted  ....! ")
            
except Exception as e:
    st.warning(f"{str(e)}")
    st.code(f"{str(e)}",language='Python')
else:
    print("no errors in the code")
    st.info("No errors in the code ")
finally:
    st.success("final block is executed succsully")