In [19]:
import numpy as np 
import pandas as pd 
from matplotlib import pyplot as plt 
import seaborn as sns 
import statistics as sts 
import scipy.spatial.distance as  dts
import streamlit as st
import joblib as jlib
from sklearn.preprocessing import StandardScaler,LabelEncoder
from sklearn.model_selection import train_test_split,cross_val_score
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score,mean_absolute_error,mean_squared_error,median_absolute_error
from sklearn.impute import SimpleImputer

from sklearn.datasets import make_regression

In [32]:
dataFrame=pd.read_csv(r"C:\Shravan\PythonPratice\houseprice\Bangalore.csv",encoding_errors='ignore')

dataFrame.isna().sum()

x=dataFrame[['Area','Location','School','BED']]
y=dataFrame['Price']

In [36]:
x

      Area                         Location  School  BED
0     3340                 JP Nagar Phase 1       0    0
1     1045       Dasarahalli on Tumkur Road       0    0
2     1179  Kannur on Thanisandra Main Road       0    0
3     1675                     Doddanekundi       0    0
4     1670                          Kengeri       0    0
...    ...                              ...     ...  ...
6202   590                       Chandapura       9    9
6203  1179                    Kasavanahalli       9    9
6204  1143                    Kasavanahalli       9    9
6205  1680                    Kasavanahalli       9    9
6206  1162                    Kasavanahalli       9    9

[6207 rows x 4 columns]

In [43]:
labelen=LabelEncoder()
dataFrame['new_location_encoded']=labelen.fit_transform(dataFrame['Location'])

In [44]:
x=dataFrame[['Area','new_location_encoded','School','BED']]
y=dataFrame['Price']
x

      Area  new_location_encoded  School  BED
0     3340                   131       0    0
1     1045                    80       0    0
2     1179                   167       0    0
3     1675                    85       0    0
4     1670                   173       0    0
...    ...                   ...     ...  ...
6202   590                    70       9    9
6203  1179                   169       9    9
6204  1143                   169       9    9
6205  1680                   169       9    9
6206  1162                   169       9    9

[6207 rows x 4 columns]

In [45]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

linear_reg=LinearRegression()
linear_reg.fit(x_train,y_train)
y_pred=linear_reg.predict(x_test)
print(y_pred)

[19997331.4805851   8185017.45550409  7676674.39914734 ...
  5867051.16162454  7772176.72675982  7752380.21047095]

In [59]:
import joblib
joblib.dump(linear_reg,"house_predications.joblib")

['house_predications.joblib']

In [49]:
x

      Area  new_location_encoded  School  BED
0     3340                   131       0    0
1     1045                    80       0    0
2     1179                   167       0    0
3     1675                    85       0    0
4     1670                   173       0    0
...    ...                   ...     ...  ...
6202   590                    70       9    9
6203  1179                   169       9    9
6204  1143                   169       9    9
6205  1680                   169       9    9
6206  1162                   169       9    9

[6207 rows x 4 columns]

In [57]:
import streamlit as st
import pandas as pd
import joblib

model = joblib.load("house_predications.joblib")
st.title("Housing Predictions")

st.sidebar.write("Enter all required details")

with st.form(key='form_details'):
    with st.sidebar:
        Area = st.number_input('Area', min_value=1100, max_value=9999, value=3340)
        new_location = st.number_input('New Location', min_value=1, max_value=999, value=70)
        school = st.number_input('School', min_value=0, max_value=10, value=8)
        Bed = st.number_input('Bed', min_value=0, max_value=10, value=1)
        submit_button = st.form_submit_button(label='Submit')

if submit_button:
    data1 = {
        'area': Area,
        'newlocation': new_location,
        'school': school,
        'bed1': Bed
    }
    df = pd.DataFrame(data1, index=[0])
    prediction = model.predict(df)
    st.write(f"The prediction value is {prediction[0]:.2f}")
    st.balloons()

2025-12-16 18:36:37.587 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-12-16 18:36:37.588 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-12-16 18:36:37.589 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-12-16 18:36:37.589 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-12-16 18:36:37.590 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-12-16 18:36:37.591 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-12-16 18:36:37.591 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-12-16 18:36:37.592 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-12-16 18:36:37.592 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-12-16 18:36:37.593 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-12-16 18:36:37.593 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-12-16 18:36:37.594 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-12-16 18:36:37.595 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-12-16 18:36:37.595 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-12-16 18:36:37.596 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-12-16 18:36:37.596 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-12-16 18:36:37.599 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-12-16 18:36:37.600 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-12-16 18:36:37.600 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-12-16 18:36:37.601 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-12-16 18:36:37.601 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-12-16 18:36:37.602 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-12-16 18:36:37.603 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-12-16 18:36:37.603 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-12-16 18:36:37.604 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-12-16 18:36:37.604 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-12-16 18:36:37.605 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-12-16 18:36:37.606 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-12-16 18:36:37.606 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-12-16 18:36:37.607 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-12-16 18:36:37.607 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-12-16 18:36:37.608 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-12-16 18:36:37.609 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-12-16 18:36:37.609 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-12-16 18:36:37.610 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-12-16 18:36:37.611 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-12-16 18:36:37.611 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-12-16 18:36:37.612 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-12-16 18:36:37.612 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-12-16 18:36:37.613 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-12-16 18:36:37.613 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-12-16 18:36:37.614 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.